### ISSUE TITLE
レスポンシブ対応

### ISSUE THREAD

**Issue by mikimhk** [bonprosoft/MSPJPWPTheme#11]
どなたか手を付けていますでしょうか？
スマホ用のワイヤーフレームを作り直した方がいいですかね(まだ完成はしてないです)

**Comment by bonprosoft** [comment]
レスポンシブを含む、サイトデザインに関する内容は、
http://github.com/bonprosoft/MSPJPWebSite
こちらへお願いします！（staging2で動いています
具体的にどのあたりが対応していないかなどを含めて、issueを個別に立てていただけると助かります
