### ISSUE TITLE
About/Contact Page design

### ISSUE THREAD

**Issue by Mizune** [bonprosoft/MSPJPWPTheme#2]
AboutページとContactページのmain__contentの背景が透過になっておらず白になっています。
仕様であればスルーしてください。(個人的には背景がもったいないかなと)

**Comment by bonprosoft** [comment]
現在確認したところ解決しているようにみえましたが、いかがでしょうか。
（キャッシュを切って閲覧してみてください）

**Comment by Mizune** [comment]
キャッシュクリア後確認しましたが変わっていないと思われます

**Comment by bonprosoft** [comment]
single.cssには.reportがrgba(255,255,255,0.7)と書かれていますが、いかがでしょうか。
![msp](https://cloud.githubusercontent.com/assets/1482237/6575565/2c3da7d2-c773-11e4-821f-cae0b9792fcf.png)

**Comment by bonprosoft** [comment]
基本的にcssはMSPWebSiteのほうで編集していただければ、それを取り入れていますので、ここでのissueは閉じますね
