### ISSUE TITLE
サイドメニューの内容

### ISSUE THREAD

**Issue by damjing** [bonprosoft/MSPJPWPTheme#3]
各ページにサイドメニューがありますが、そこで表示すべきものは何なのか、それとそもそもそのページにサイドメニューが必要なのかどうかの検討をしないといけない気がします。

**Comment by damjing** [comment]
ちょこっと案を置いていきます。
・プロフィールページ
#所属チームごとにメンバーを一覧表示できるように、カテゴリ分け的な感じのやつ
#プロフィールページ内で検索できるようにした検索窓

**Comment by damjing** [comment]
3/13 プロジェクトページのは完了

**Comment by damjing** [comment]
3/13 : プロジェクト一覧は表示できた。現在のページのところ、色付けて白文字にしたい。

**Comment by bonprosoft** [comment]
このあたりはWebSiteと協力しましょうか
https://github.com/bonprosoft/MSPJPWebSite/issues/14
