### ISSUE TITLE
各プロジェクトの詳細ページ

### ISSUE THREAD

**Issue by damjing** [bonprosoft/MSPJPWPTheme#4]
・カテゴリー表示は必要か否か
・著者の表示は必要か否か(Last update: でもいいかなぁと)
・更新日の表示は冒頭にあるべきか最後にあるべきか

**Comment by damjing** [comment]
こじんてきにはカテゴリーは表示しなくてもいいかなぁと思ってます。
更新日の表示位置は迷う…って感じなんですがいかがでしょうか？

**Comment by bonprosoft** [comment]
著者の表示はいらないと思います
カテゴリー表示、ってプロジェクトにカスタムタクソノミーってありましたっけ？
更新日は上にあったほうが分かりやすくてよいと思います
